### ISSUE TITLE
Specifying locale specific text in options

### ISSUE THREAD

**Issue by milansimek** [emotionLoop/visualCaptcha-frontend-jquery#8]
Hi,

Is it possible to specify language specific strings in the initialization options?

I'm currently using different .json files for the image descriptions, but I'd also like to change the 'click or touch ... ' text.

Please note that the text needs to be dynamically adjusted based on the current locale, so hard coding the text isn't an option.

I was thinking of adding a global object with translation strings. I suspect there should be a more elegant solution for this problem though.

Thanks a bunch! Excellent plugin.

**Comment by BrunoBernardino** [comment]
Hi @milansimek !

You can definitely do it. Code example is at https://github.com/emotionLoop/visualCaptcha-frontend-core#visualcaptcha-options in the `language` property.

Because you want it to be dynamic, I'd suggest you build something that puts the correct language options in there when initializing it.

I cannot make this a default part of visualCaptcha, though, because people have many different valid implementations.

Let me know if I can be of any further help!

**Comment by milansimek** [comment]
Perfect, thanks a lot!
